name: KeepMoving
version: ${project.version}
main: net.kunmc.lab.keepmoving.KeepMoving
api-version: 1.15
commands:
  keepmoving:
      description: commands to adjust delay time
      usage: |
        /<command> delay [value(int)] - set delay(default: 4)
        /<command> liquidDelay [value(int)] - set delay when players are in liquid(default: 14)
      permission: op
